# Generated by Django 5.2.4 on 2025-08-20 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auth_system', '0001_initial'),
        ('ems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbluser',
            name='branch_id',
            field=models.ForeignKey(db_column='branch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ems.tblbranch'),
        ),
        migrations.AddField(
            model_name='tbluser',
            name='department_id',
            field=models.ForeignKey(db_column='department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ems.tbldepartment'),
        ),
        migrations.AddField(
            model_name='tbluser',
            name='designation_id',
            field=models.ForeignKey(db_column='designation_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ems.tbldesignation'),
        ),
        migrations.AddField(
            model_name='tbluser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='tbluser',
            name='role_id',
            field=models.ForeignKey(db_column='role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ems.role'),
        ),
        migrations.AddField(
            model_name='tbluser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='apilog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_system_apilogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blacklistedtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lastthreepasswords',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loginsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='blacklistedtoken',
            unique_together={('token', 'user')},
        ),
        migrations.AddIndex(
            model_name='loginsession',
            index=models.Index(fields=['user', 'logout_at'], name='auth_system_user_id_04142c_idx'),
        ),
    ]
