# Generated by Django 5.2 on 2025-08-25 07:26

import django.db.models.deletion
import django.utils.timezone
import lead.models.enquiry_images
import lead.models.enquiry_selfie
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ems", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain_url", models.CharField(max_length=255)),
                ("privacy_policy", models.CharField(max_length=255)),
                ("terms_and_condition_url", models.CharField(max_length=255)),
                ("about_url", models.CharField(max_length=255)),
                ("contact_us", models.CharField(max_length=255)),
                ("created_by", models.IntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_by", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("deleted_by", models.IntegerField(blank=True, default=0, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "lead_configurations",
            },
        ),
        migrations.CreateModel(
            name="LoanAmountRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loan_amount_from", models.IntegerField(blank=True, null=True)),
                ("loan_amount_to", models.IntegerField(blank=True, null=True)),
                ("created_by", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("deleted_by", models.IntegerField(blank=True, default=0, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Loan Amount Range",
                "verbose_name_plural": "Loan Amount Ranges",
                "db_table": "lead_loan_amount_range",
            },
        ),
        migrations.CreateModel(
            name="NatureOfBusiness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created_by", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("deleted_by", models.IntegerField(blank=True, default=0, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "lead_nature_of_business",
            },
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created_by", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("deleted_by", models.IntegerField(blank=True, default=0, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "lead_product_type",
            },
        ),
        migrations.CreateModel(
            name="PropertyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created_by", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("deleted_by", models.IntegerField(blank=True, default=0, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "lead_property_document",
            },
        ),
        migrations.CreateModel(
            name="PropertyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created_by", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("deleted_by", models.IntegerField(blank=True, default=0, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "lead_property_type",
            },
        ),
        migrations.CreateModel(
            name="APILog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uniqid", models.UUIDField(db_index=True, editable=False)),
                ("method", models.CharField(max_length=10)),
                ("endpoint", models.CharField(max_length=255)),
                ("request_data", models.JSONField(blank=True, null=True)),
                ("response_status", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_apilogs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("mobile_number", models.CharField(max_length=15)),
                ("lan_number", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "occupation",
                    models.IntegerField(
                        choices=[(1, "salaried"), (2, "Self-Employed")], default=1
                    ),
                ),
                (
                    "employer_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("number_of_years_service", models.IntegerField(blank=True, null=True)),
                (
                    "official_contact_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "nature_of_service",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "monthly_income",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "business_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "business_place",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "business_contact_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "nature_of_business",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "income",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("interested", models.BooleanField(default=False)),
                ("kyc_collected", models.BooleanField(default=False)),
                (
                    "kyc_document",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("kyc_number", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "is_steps",
                    models.IntegerField(
                        choices=[
                            (1, "Basic"),
                            (2, "Address"),
                            (3, "Loan_Detail"),
                            (4, "Verification"),
                            (5, "Image"),
                            (6, "Selfie"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "is_status",
                    models.IntegerField(
                        choices=[
                            (0, "Draft"),
                            (1, "Submitted"),
                            (2, "Active"),
                            (3, "Closed"),
                            (4, "Reject"),
                            (5, "Re Open"),
                        ],
                        default=0,
                    ),
                ),
                ("created_by", models.IntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_by", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("deleted_by", models.IntegerField(blank=True, default=0, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assign_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ems.tblempbasicprofile",
                    ),
                ),
                (
                    "loan_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lead.producttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnquiryAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("premises_type", models.CharField(max_length=100)),
                ("premises_status", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("pincode", models.CharField(max_length=10)),
                ("latitude", models.CharField(blank=True, max_length=200, null=True)),
                ("longitude", models.CharField(blank=True, max_length=200, null=True)),
                ("state", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("area", models.CharField(max_length=255)),
                ("use_different_address", models.BooleanField(default=False)),
                (
                    "different_premises_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "different_premises_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("different_address", models.TextField(blank=True, null=True)),
                (
                    "different_pincode",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "different_latitude",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "different_longitude",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "different_state",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "different_district",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "different_area",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_by", models.IntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_by", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("deleted_by", models.IntegerField(blank=True, default=0, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "enquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enquiry_addresses",
                        to="lead.enquiry",
                    ),
                ),
            ],
            options={
                "db_table": "lead_enquiry_address",
            },
        ),
        migrations.CreateModel(
            name="EnquiryImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.IntegerField()),
                ("capture_date", models.DateField(editable=False)),
                ("capture_time", models.TimeField(editable=False)),
                ("ip_addresses", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("document_types", models.IntegerField()),
                ("document_sub_types", models.IntegerField()),
                ("premises_type", models.IntegerField()),
                (
                    "media_file",
                    models.FileField(
                        upload_to=lead.models.enquiry_images.image_upload_path
                    ),
                ),
                ("created_by", models.IntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_by", models.IntegerField(blank=True, default=0, null=True)),
                ("updated_at", models.DateTimeField(blank=None, null=True)),
                ("deleted_by", models.IntegerField(blank=True, default=0, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "enquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enquiry_images",
                        to="lead.enquiry",
                    ),
                ),
            ],
            options={
                "db_table": "lead_enquiry_image",
            },
        ),
        migrations.CreateModel(
            name="EnquirySelfie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("premises_type", models.CharField(max_length=100)),
                ("employee_id", models.IntegerField()),
                ("capture_date", models.DateField(editable=False)),
                ("capture_time", models.TimeField(editable=False)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "selfie1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=lead.models.enquiry_selfie.selfies_upload_path,
                    ),
                ),
                (
                    "selfie2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=lead.models.enquiry_selfie.selfies_upload_path,
                    ),
                ),
                (
                    "selfie3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=lead.models.enquiry_selfie.selfies_upload_path,
                    ),
                ),
                (
                    "selfie4",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=lead.models.enquiry_selfie.selfies_upload_path,
                    ),
                ),
                (
                    "selfie5",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=lead.models.enquiry_selfie.selfies_upload_path,
                    ),
                ),
                (
                    "selfie6",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=lead.models.enquiry_selfie.selfies_upload_path,
                    ),
                ),
                ("created_by", models.IntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_by", models.IntegerField(blank=True, default=0, null=True)),
                ("updated_at", models.DateTimeField(blank=None, null=True)),
                ("deleted_by", models.IntegerField(blank=True, default=0, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "enquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enquiry_selfies",
                        to="lead.enquiry",
                    ),
                ),
            ],
            options={
                "db_table": "lead_enquiry_selfie",
            },
        ),
        migrations.CreateModel(
            name="EnquiryVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "mobile_status",
                    models.IntegerField(
                        choices=[(0, "Pending"), (1, "Verified"), (2, "Skipped")],
                        default=0,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "email_verified",
                    models.IntegerField(
                        choices=[(0, "Pending"), (1, "Verified"), (2, "Skipped")],
                        default=0,
                    ),
                ),
                ("aadhaar", models.CharField(blank=True, max_length=20, null=True)),
                ("aadhaar_verified", models.BooleanField(default=False)),
                ("created_by", models.IntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_by", models.IntegerField(blank=True, default=0, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.IntegerField(blank=True, default=0, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "enquiry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enquiry_verification",
                        to="lead.enquiry",
                    ),
                ),
            ],
            options={
                "db_table": "lead_enquiry_verifications",
            },
        ),
        migrations.CreateModel(
            name="LeadAssignLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remark", models.TextField(blank=True, null=True)),
                ("created_by", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("deleted_by", models.IntegerField(blank=True, default=0, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ems.tblbranch",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ems.tblempbasicprofile",
                    ),
                ),
                (
                    "enquiry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lead.enquiry",
                    ),
                ),
            ],
            options={
                "db_table": "lead_assign_logs",
            },
        ),
        migrations.CreateModel(
            name="LeadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (0, "Draft"),
                            (1, "Submitted"),
                            (2, "Active"),
                            (3, "Closed"),
                            (4, "Reject"),
                            (5, "Re Open"),
                        ],
                        default=0,
                        max_length=50,
                    ),
                ),
                ("remark", models.TextField(blank=True, null=True)),
                ("followup_pickup_date", models.DateField(blank=True, null=True)),
                ("created_by", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("deleted_by", models.IntegerField(blank=True, default=0, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "enquiry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lead.enquiry",
                    ),
                ),
            ],
            options={
                "db_table": "lead_logs",
            },
        ),
        migrations.CreateModel(
            name="EnquiryLoanDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sale_deed_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "agreement_sell_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "property_document_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "akhive_patrika",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "property_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "loan_required_on",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Income"), (2, "Vehicle"), (3, "Property")],
                        null=True,
                    ),
                ),
                (
                    "vehicle_registration_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "income_document",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("followup_pickup_date", models.DateField(blank=True, null=True)),
                (
                    "enquiry_type",
                    models.IntegerField(
                        blank=True, choices=[(1, "Hot"), (2, "Cold")], null=True
                    ),
                ),
                ("remark", models.TextField(blank=True, null=True)),
                ("created_by", models.IntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_by", models.IntegerField(blank=True, default=0, null=True)),
                ("updated_at", models.DateTimeField(blank=None, null=True)),
                ("deleted_by", models.IntegerField(blank=True, default=0, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "enquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enquiry_loan_details",
                        to="lead.enquiry",
                    ),
                ),
                (
                    "loan_amount_range",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lead.loanamountrange",
                    ),
                ),
                (
                    "loan_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lead.producttype",
                    ),
                ),
                (
                    "property_document_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lead.propertydocument",
                    ),
                ),
                (
                    "property_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lead.propertytype",
                    ),
                ),
            ],
            options={
                "db_table": "lead_enquiry_load_details",
            },
        ),
    ]
