# Generated by Django 5.2 on 2025-08-25 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enquiryimages",
            old_name="ip_addresses",
            new_name="ip_address",
        ),
    ]
