# Generated by Django 5.2 on 2025-08-25 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0002_rename_ip_addresses_enquiryimages_ip_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enquiryselfie",
            old_name="selfie1",
            new_name="selfie",
        ),
        migrations.RemoveField(
            model_name="enquiryselfie",
            name="selfie2",
        ),
        migrations.RemoveField(
            model_name="enquiryselfie",
            name="selfie3",
        ),
        migrations.RemoveField(
            model_name="enquiryselfie",
            name="selfie4",
        ),
        migrations.RemoveField(
            model_name="enquiryselfie",
            name="selfie5",
        ),
        migrations.RemoveField(
            model_name="enquiryselfie",
            name="selfie6",
        ),
    ]
