# Generated by Django 4.2.23 on 2025-08-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0004_alter_leadlog_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiryimages",
            name="document_sub_types",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
