# Generated by Django 4.2.23 on 2025-09-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0005_alter_enquiryimages_document_sub_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiry",
            name="lan_number",
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
