# Generated by Django 4.2.23 on 2025-09-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0006_alter_enquiry_lan_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiry",
            name="lan_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
