# Generated by Django 4.2.23 on 2025-09-02 06:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0007_alter_enquiry_lan_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enquiryverification",
            old_name="email_verified",
            new_name="email_status",
        ),
    ]
