# Generated by Django 4.2.23 on 2025-09-04 12:00

from django.db import migrations, models
import django.utils.timezone
import lead.models.enquiry_tickets


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0008_rename_email_verified_enquiryverification_email_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnquiryTickets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "attachment",
                    models.FileField(
                        upload_to=lead.models.enquiry_tickets.attachment_path
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "Low"), (2, "Medium"), (3, "High")]
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "OPEN"), (2, "CLOSED"), (3, "ACTIVE")], default=1
                    ),
                ),
                ("created_by", models.IntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_by", models.IntegerField(blank=True, default=0, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.IntegerField(blank=True, default=0, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "lead_enquiry_tickets",
            },
        ),
    ]
