# Generated by Django 4.2.23 on 2025-09-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0009_enquirytickets"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnquiryEnduser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("created_by", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("deleted_by", models.IntegerField(blank=True, default=0, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "lead_enquiry_end_user",
            },
        ),
        migrations.AlterField(
            model_name="enquirytickets",
            name="status",
            field=models.IntegerField(
                choices=[(1, "OPEN"), (2, "CLOSED"), (3, "ACTIVE"), (4, "REJECT")],
                default=1,
            ),
        ),
    ]
