# Generated by Django 4.2.23 on 2025-09-09 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0010_enquiryenduser_alter_enquirytickets_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiryloandetails",
            name="end_user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lead.enquiryenduser",
            ),
        ),
    ]
