# Generated by Django 4.2.23 on 2025-09-09 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0011_enquiryloandetails_end_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiry",
            name="nature_of_business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lead.natureofbusiness",
            ),
        ),
    ]
