# Generated by Django 4.2.23 on 2025-09-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0012_alter_enquiry_nature_of_business"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiryenduser",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
