# Generated by Django 4.2.23 on 2025-09-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0013_alter_enquiryenduser_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enquiryimages",
            old_name="employee_id",
            new_name="employee_code",
        ),
        migrations.RenameField(
            model_name="enquiryselfie",
            old_name="employee_id",
            new_name="employee_code",
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="is_status",
            field=models.IntegerField(
                choices=[
                    (0, "Draft"),
                    (1, "Active"),
                    (2, "Closed"),
                    (3, "Reject"),
                    (4, "Re Open"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="enquiryimages",
            name="premises_type",
            field=models.CharField(max_length=100),
        ),
    ]
