# Generated by Django 4.2.23 on 2025-09-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0014_rename_employee_id_enquiryimages_employee_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiryimages",
            name="employee_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="enquiryselfie",
            name="employee_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
