# Generated by Django 4.2.23 on 2025-09-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0015_alter_enquiryimages_employee_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiry",
            name="is_steps",
            field=models.IntegerField(
                choices=[
                    (1, "Basic"),
                    (2, "Address"),
                    (3, "Verification"),
                    (4, "Loan_Detail"),
                    (5, "Image"),
                    (6, "Selfie"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="kyc_document",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Aadhar"),
                    (2, "Pan Card"),
                    (3, "Voter Id"),
                    (4, "driving License"),
                ],
                null=True,
            ),
        ),
    ]
