# Generated by Django 4.2.23 on 2025-09-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0016_alter_enquiry_is_steps_alter_enquiry_kyc_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiry",
            name="unique_code",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
