# Generated by Django 4.2.23 on 2025-09-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ems", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tblempaddressdetails",
            name="address",
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name="tblempaddressdetails",
            name="city",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="tblempaddressdetails",
            name="district",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="tblempaddressdetails",
            name="pincode",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="tblempaddressdetails",
            name="state",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
