# Generated by Django 6.0.4 on 2026-04-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0002_alter_tblempaddressdetails_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblbranch',
            name='state_group_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tblempbasicprofile',
            name='whatsapp_mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
